package com.solonari.igor.currency;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public class Utils {

    public static final Map<String, String> dictionary;

    static {
        Map<String, String> map = new HashMap<>();
        map.put("AFN", "Afghani");
        map.put("EUR", "Euro");
        map.put("ALL", "Lek");
        map.put("DZD", "Algerian Dinar");
        map.put("USD", "US Dollar");
        map.put("AOA", "Kwanza");
        map.put("XCD", "East Caribbean Dollar");
        map.put("ARS", "Argentine Peso");
        map.put("AMD", "Armenian Dram");
        map.put("AWG", "Aruban Florin");
        map.put("AUD", "Australian Dollar");
        map.put("AZN", "Azerbaijan Manat");
        map.put("BSD", "Bahamian Dollar");
        map.put("BHD", "Bahraini Dinar");
        map.put("BDT", "Taka");
        map.put("BBD", "Barbados Dollar");
        map.put("BYN", "Belarusian Ruble");
        map.put("BZD", "Belize Dollar");
        map.put("XOF", "CFA Franc BCEAO");
        map.put("BMD", "Bermudian Dollar");
        map.put("INR", "Indian Rupee");
        map.put("BTN", "Ngultrum");
        map.put("BOB", "Boliviano");
        map.put("BOV", "Mvdol");
        map.put("BAM", "Convertible Mark");
        map.put("BWP", "Pula");
        map.put("NOK", "Norwegian Krone");
        map.put("BRL", "Brazilian Real");
        map.put("BND", "Brunei Dollar");
        map.put("BGN", "Bulgarian Lev");
        map.put("BIF", "Burundi Franc");
        map.put("CVE", "Cabo Verde Escudo");
        map.put("KHR", "Riel");
        map.put("XAF", "CFA Franc BEAC");
        map.put("CAD", "Canadian Dollar");
        map.put("KYD", "Cayman Islands Dollar");
        map.put("CLP", "Chilean Peso");
        map.put("CLF", "Unidad de Fomento");
        map.put("CNY", "Yuan Renminbi");
        map.put("COP", "Colombian Peso");
        map.put("COU", "Unidad de Valor Real");
        map.put("KMF", "Comorian Franc ");
        map.put("CDF", "Congolese Franc");
        map.put("NZD", "New Zealand Dollar");
        map.put("CRC", "Costa Rican Colon");
        map.put("HRK", "Kuna");
        map.put("CUP", "Cuban Peso");
        map.put("CUC", "Peso Convertible");
        map.put("ANG", "Netherlands Antillean Guilder");
        map.put("CZK", "Czech Koruna");
        map.put("DKK", "Danish Krone");
        map.put("DJF", "Djibouti Franc");
        map.put("DOP", "Dominican Peso");
        map.put("EGP", "Egyptian Pound");
        map.put("SVC", "El Salvador Colon");
        map.put("ERN", "Nakfa");
        map.put("ETB", "Ethiopian Birr");
        map.put("FKP", "Falkland Islands Pound");
        map.put("FJD", "Fiji Dollar");
        map.put("XPF", "CFP Franc");
        map.put("GMD", "Dalasi");
        map.put("GEL", "Lari");
        map.put("GHS", "Ghana Cedi");
        map.put("GIP", "Gibraltar Pound");
        map.put("GTQ", "Quetzal");
        map.put("GBP", "Pound Sterling");
        map.put("GNF", "Guinean Franc");
        map.put("GYD", "Guyana Dollar");
        map.put("HTG", "Gourde");
        map.put("HNL", "Lempira");
        map.put("HKD", "Hong Kong Dollar");
        map.put("HUF", "Forint");
        map.put("ISK", "Iceland Krona");
        map.put("IDR", "Rupiah");
        map.put("XDR", "SDR (Special Drawing Right)");
        map.put("IRR", "Iranian Rial");
        map.put("IQD", "Iraqi Dinar");
        map.put("ILS", "New Israeli Sheqel");
        map.put("JMD", "Jamaican Dollar");
        map.put("JPY", "Yen");
        map.put("JOD", "Jordanian Dinar");
        map.put("KZT", "Tenge");
        map.put("KES", "Kenyan Shilling");
        map.put("KPW", "North Korean Won");
        map.put("KRW", "Won");
        map.put("KWD", "Kuwaiti Dinar");
        map.put("KGS", "Som");
        map.put("LAK", "Lao Kip");
        map.put("LBP", "Lebanese Pound");
        map.put("LSL", "Loti");
        map.put("ZAR", "Rand");
        map.put("LRD", "Liberian Dollar");
        map.put("LYD", "Libyan Dinar");
        map.put("CHF", "Swiss Franc");
        map.put("MOP", "Pataca");
        map.put("MKD", "Denar");
        map.put("MGA", "Malagasy Ariary");
        map.put("MWK", "Malawi Kwacha");
        map.put("MYR", "Malaysian Ringgit");
        map.put("MVR", "Rufiyaa");
        map.put("MRU", "Ouguiya");
        map.put("MUR", "Mauritius Rupee");
        map.put("XUA", "ADB Unit of Account");
        map.put("MXN", "Mexican Peso");
        map.put("MXV", "Mexican Unidad de Inversion (UDI)");
        map.put("MDL", "Moldovan Leu");
        map.put("MNT", "Tugrik");
        map.put("MAD", "Moroccan Dirham");
        map.put("MZN", "Mozambique Metical");
        map.put("MMK", "Kyat");
        map.put("NAD", "Namibia Dollar");
        map.put("NPR", "Nepalese Rupee");
        map.put("NIO", "Cordoba Oro");
        map.put("NGN", "Naira");
        map.put("OMR", "Rial Omani");
        map.put("PKR", "Pakistan Rupee");
        map.put("PAB", "Balboa");
        map.put("PGK", "Kina");
        map.put("PYG", "Guarani");
        map.put("PEN", "Sol");
        map.put("PHP", "Philippine Peso");
        map.put("PLN", "Zloty");
        map.put("QAR", "Qatari Rial");
        map.put("RON", "Romanian Leu");
        map.put("RUB", "Russian Ruble");
        map.put("RWF", "Rwanda Franc");
        map.put("SHP", "Saint Helena Pound");
        map.put("WST", "Tala");
        map.put("STN", "Dobra");
        map.put("SAR", "Saudi Riyal");
        map.put("RSD", "Serbian Dinar");
        map.put("SCR", "Seychelles Rupee");
        map.put("SLL", "Leone");
        map.put("SGD", "Singapore Dollar");
        map.put("XSU", "Sucre");
        map.put("SBD", "Solomon Islands Dollar");
        map.put("SOS", "Somali Shilling");
        map.put("SSP", "South Sudanese Pound");
        map.put("LKR", "Sri Lanka Rupee");
        map.put("SDG", "Sudanese Pound");
        map.put("SRD", "Surinam Dollar");
        map.put("SZL", "Lilangeni");
        map.put("SEK", "Swedish Krona");
        map.put("CHE", "WIR Euro");
        map.put("CHW", "WIR Franc");
        map.put("SYP", "Syrian Pound");
        map.put("TWD", "New Taiwan Dollar");
        map.put("TJS", "Somoni");
        map.put("TZS", "Tanzanian Shilling");
        map.put("THB", "Baht");
        map.put("TOP", "Pa’anga");
        map.put("TTD", "Trinidad and Tobago Dollar");
        map.put("TND", "Tunisian Dinar");
        map.put("TRY", "Turkish Lira");
        map.put("TMT", "Turkmenistan New Manat");
        map.put("UGX", "Uganda Shilling");
        map.put("UAH", "Hryvnia");
        map.put("AED", "UAE Dirham");
        map.put("USN", "US Dollar (Next day)");
        map.put("UYU", "Peso Uruguayo");
        map.put("UYI", "Uruguay Peso en Unidades Indexadas (UI)");
        map.put("UYW", "Unidad Previsional");
        map.put("UZS", "Uzbekistan Sum");
        map.put("VUV", "Vatu");
        map.put("VES", "Bolívar Soberano");
        map.put("VND", "Dong");
        map.put("YER", "Yemeni Rial");
        map.put("ZMW", "Zambian Kwacha");
        map.put("ZWL", "Zimbabwe Dollar");
        map.put("XBA", "Bond Markets Unit European Composite Unit (EURCO)");
        map.put("XBB", "Bond Markets Unit European Monetary Unit (E.M.U.-6)");
        map.put("XBC", "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)");
        map.put("XBD", "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)");
        map.put("XTS", "Codes specifically reserved for testing purposes");
        map.put("XAU", "Gold");
        map.put("XPD", "Palladium");
        map.put("XPT", "Platinum");
        map.put("XAG", "Silver");

        dictionary = Collections.unmodifiableMap(map);
    }
}
